---

is_debug: false
time_zone: Europe/Madrid
accept_unknown_tag: false
accept_unknown_chp: false
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 5000
  tls_enabled: true
  cert_file: c:/cert/cert.pem
  key_file: c:/cert/key.pem
api:
  bind_ip: 0.0.0.0
  port: 5001
  tls_enabled: true
  cert_file: c:/cert/cert.pem
  key_file: c:/cert/key.pem
metrics:
  enabled: true
  bind_ip: 127.0.0.1
  port: 5003
mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  user: admin
  password: pass
  database: evsys
payment:
  enabled: false
  api_url: 127.0.0.1:5002
  api_key: PAYMENT_API_KEY
telegram:
  enabled: false
  telegram_api_key: YOUR_TELEGRAM_API_KEY