name: Deploy to wattbrews.me

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare configuration file
        run: |
          sed -i 's|${TIME_ZONE}|'"$TIME_ZONE"'|g' evsys.yml
          sed -i 's|${PORT}|'"$PORT"'|g' evsys.yml
          sed -i 's|${TLS_ENABLED}|'"$TLS_ENABLED"'|g' evsys.yml
          sed -i 's|${API_PORT}|'"$API_PORT"'|g' evsys.yml
          sed -i 's|${API_TLS_ENABLED}|'"$API_TLS_ENABLED"'|g' evsys.yml
          sed -i 's|${CERT_FILE}|'"$CERT_FILE"'|g' evsys.yml
          sed -i 's|${KEY_FILE}|'"$KEY_FILE"'|g' evsys.yml
          sed -i 's|${METRICS_PORT}|'"$METRICS_PORT"'|g' evsys.yml
          sed -i 's|${MONGO_HOST}|'"$MONGO_HOST"'|g' evsys.yml
          sed -i 's|${MONGO_PORT}|'"$MONGO_PORT"'|g' evsys.yml
          sed -i 's|${MONGO_USER}|'"$MONGO_USER"'|g' evsys.yml
          sed -i 's|${MONGO_PASS}|'"$MONGO_PASS"'|g' evsys.yml
          sed -i 's|${MONGO_DB}|'"$MONGO_DB"'|g' evsys.yml
          sed -i 's|${PAYMENT_API_URL}|'"$PAYMENT_API_URL"'|g' evsys.yml
          sed -i 's|${PAYMENT_API_KEY}|'"$PAYMENT_API_KEY"'|g' evsys.yml
          sed -i 's|${TELEGRAM_API_KEY}|'"$TELEGRAM_API_KEY"'|g' evsys.yml
          sed -i 's|${OCPI_URL}|'"$OCPI_URL"'|g' evsys.yml
          sed -i 's|${OCPI_TOKEN}|'"$OCPI_TOKEN"'|g' evsys.yml
        env:
          TIME_ZONE: ${{ vars.TIME_ZONE }}
          PORT: ${{ vars.PORT }}
          TLS_ENABLED: ${{ vars.TLS_ENABLED }}
          API_PORT: ${{ vars.API_PORT }}
          API_TLS_ENABLED: ${{ vars.API_TLS_ENABLED }}
          CERT_FILE: ${{ vars.CERT_FILE }}
          KEY_FILE: ${{ vars.KEY_FILE }}
          METRICS_PORT: ${{ vars.METRICS_PORT }}
          MONGO_HOST: ${{ vars.MONGO_HOST }}
          MONGO_PORT: ${{ vars.MONGO_PORT }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_DB: ${{ vars.MONGO_DB }}
          PAYMENT_API_URL: ${{ secrets.PAYMENT_API_URL }}
          PAYMENT_API_KEY: ${{ secrets.PAYMENT_API_KEY }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          OCPI_URL: ${{ vars.OCPI_URL }}
          OCPI_TOKEN: ${{ secrets.OCPI_TOKEN }}

      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "evsys.yml"
          target: "/etc/conf/"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go application
        run: |
          go build -v -o evsys

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "evsys"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart evsys.service 
